### ISSUE TITLE
実行出来ない

### ISSUE THREAD

**Issue by t-hatanaka** [Project-PLATEAU/PLATEAU-TwinLink#2]
チュートリアルの環境構築手順に従って、都市データを登録し実行パッケージ化して生成されたEXEを実行しましたが、
UE5がcrashし、Fatal error!　となります。

実行環境は、Windows10、UE5（5.3.2）です。
都市データを登録する前に、再生ボタンを押下してもクラッシュします。

**Comment by Ronnel216** [comment]
@t-hatanaka 様
エラーの報告ありがとうございます。

https://github.com/Synesthesias/PLATEAU-TwinLink/tree/Fix/crashes_during_execution
上記のブランチにて修正を行いました。
現在、こちらのブランチにプルリクエスト中です。

以下は補足です。
> 都市データを登録する前に、再生ボタンを押下してもクラッシュします。

環境構築手順書に記載された工程をすべて行う必要があります。

> 実行環境は、Windows10、UE5（5.3.2）です。

推奨環境はWindows11です。

以上です。
よろしくお願いいたします。

追記
修正内容はこちらのブランチにマージ済みです。

**Comment by t-hatanaka** [comment]
再生してもクラッシュしないことを確認出来ました。
また、パッケージ化して、EXEの起動も出来るようになりました。
有難う御座います。
